export const GET_CUSTOMER_REQUEST = "GET_CUSTOMER_REQUEST"
export const GET_CUSTOMER_SUCCESS = "GET_CUSTOMER_SUCCESS"
export const GET_CUSTOMER_FAILURE= "GET_CUSTOMER_FAILURE"

export const POST_CUSTOMER_SUCCESS = "POST_CUSTOMER_SUCCESS"
export const POST_CUSTOMER_FAILURE= "POST_CUSTOMER_FAILURE"
export const POST_CUSTOMER_REQUEST = "POST_CUSTOMER_REQUEST"